# Generated by Django 4.1.3 on 2023-03-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botfunctions',
            old_name='name',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='botfunctions',
            name='code',
        ),
        migrations.AddField(
            model_name='botfunctions',
            name='func_name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
