# Generated by Django 4.2 on 2023-04-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_botpresets_delete_usersbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botpresets',
            name='bot_id',
        ),
        migrations.AddField(
            model_name='botpresets',
            name='bot_name',
            field=models.CharField(default=str, max_length=32),
            preserve_default=False,
        ),
    ]
