# Generated by Django 4.2 on 2023-04-30 13:52
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_remove_botpresets_bot_id_botpresets_bot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='botpresets',
            name='created_at',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
