# Generated by Django 4.1.7 on 2023-05-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_remove_botpresets_file_name_funcforpresets'),
    ]

    operations = [
        migrations.AddField(
            model_name='botpresets',
            name='token',
            field=models.CharField(default=str, max_length=64),
            preserve_default=False,
        ),
    ]
