# Generated by Django 4.1.7 on 2023-05-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_botpresets_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='botpresets',
            name='os',
            field=models.CharField(default=str, max_length=4),
            preserve_default=False,
        ),
    ]
