# Generated by Django 4.1.7 on 2023-05-07 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_botpresets_os'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcforpresets',
            old_name='func',
            new_name='func_name',
        ),
    ]
