# Generated by Django 4.2 on 2023-05-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_alter_botpresets_os'),
        ('first', '0009_rename_func_funcforpresets_func_name'),
    ]

    operations = [
    ]
