# Generated by Django 4.2 on 2023-05-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_rename_func_funcforpresets_func_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botpresets',
            name='os',
            field=models.CharField(max_length=10),
        ),
    ]
