# Generated by Django 4.2 on 2023-05-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_alter_botpresets_os'),
        ('first', '0010_merge_20230508_1457'),
    ]

    operations = [
    ]
